myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:book_id>', views.detail, name='detail'),
    path(r'findbooks/', views.findbooks, name='findbooks'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'review/', views.review, name='review'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'chk_reviews/<int:book_id>', views.chk_reviews, name='chk_reviews'),
    ]

mysiteF19/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', views.about, name='about'),
    #path(r'myapp/', include('myapp.urls1')),
    path(r'myapp/', include('myapp.urls')),
]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here--------------
class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, default='USA')

    def __str__(self):
        return self.name


class Book(models.Model):
    CATEGORY_CHOICES = [
        ('S', 'Science&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default='S')
    num_pages = models.PositiveIntegerField(default=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    publisher = models.ForeignKey(Publisher, related_name='books', on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Member(User):
    STATUS_CHOICES = {
        (1, 'Regular member'),
        (2, 'Premium Member'),
        (3, 'Guest Member'),
    }

    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    address = models.CharField(max_length=300, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, default='ON')
    last_renewal = models.DateField(default=timezone.now)
    auto_renew = models.BooleanField(default=True)
    borrowed_books = models.ManyToManyField(Book, blank=True)


class Order(models.Model):
    ORDER_CHOICES = [
        (0, 'Purchase'),
        (1, 'Borrow')
    ]
    books = models.ManyToManyField(Book)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    order_type = models.IntegerField(choices=ORDER_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)

    def total_items(self):
        return len(self.books.all())

    def __str__(self):
        return str(self.id) + " " + str(self.order_date)


class Review(models.Model):
    reviewer = models.EmailField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True, null=True)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.id) + " " + str(self.date)

myapp/forms.py
from django import forms
from myapp.models import Order, Review


class SearchForm(forms.Form):
    CATEGORY_CHOICES = [
        ('S', 'Science&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    name = forms.CharField(label="Your Name", max_length=100, required=False)
    category = forms.ChoiceField(label="Select a Category", widget=forms.RadioSelect, choices=CATEGORY_CHOICES,
                                 required=False)
    max_price = forms.IntegerField(label="Maximum Price", min_value=0)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['books', 'member', 'order_type']
        widgets = {'books': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect}
        labels = {'member': u'Member name', }


class ReviewForm(forms.ModelForm):
    class Meta:

        model = Review
        fields = ['reviewer', 'book', 'rating', 'comments']
        widgets = {'reviewer': forms.EmailInput(),
                   'book': forms.RadioSelect(),
                   'rating': forms.NumberInput(),
                   'comments': forms.Textarea()
                   }
        labels = {'reviewer': u"Please enter a valid Email Id", 'rating': u"Rating: An integer between 1 (worst) and 5 (best)"}

myapp/views.py
import datetime
import random

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Book, Member, Review
from django.http import HttpResponse, HttpResponseRedirect
from .forms import SearchForm, OrderForm, ReviewForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test


# Create your views here.
def index(request):
    if 'last_login' in request.session:
        last_login = request.session['last_login']
    else:
        last_login = 'Your last login was more that one hour ago'
    booklist = Book.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'booklist': booklist,'last_login':last_login})


def about(request):
    cookie_found = False
    if request.COOKIES.get('lucky_num'):
        myLuckyNum = request.COOKIES.get('lucky_num')
        cookie_found = True

    else:
        myLuckyNum = random.randint(1, 100)

    response = render(request, 'myapp/about.html', {'myLuckyNum': myLuckyNum})
    if not cookie_found:
        response.set_cookie('lucky_num', myLuckyNum, 300)
    return response


def detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'myapp/detail.html', {'book': book})


def findbooks(request):
    CATEGORY_CHOICES = {
        'S': 'Science&Tech',
        'F': 'Fiction',
        'B': 'Biography',
        'T': 'Travel',
        'O': 'Other'
    }
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            category = form.cleaned_data['category']
            max_price = form.cleaned_data['max_price']
            if (category):
                booklist = Book.objects.filter(category=category, price__lte=max_price)
                return render(request, 'myapp/results.html',
                              {'booklist': booklist, 'name': name, 'category': CATEGORY_CHOICES[category],
                               'max_price': max_price})
            else:
                booklist = Book.objects.filter(price__lte=max_price)
                return render(request, 'myapp/results.html',
                              {'booklist': booklist, 'name': name, 'max_price': max_price})

        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, 'myapp/findbooks.html', {'form': form})


def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            books = form.cleaned_data['books']
            # order = form.save(commit=False)
            member = order.member
            type = order.order_type
            order.save()
            form.save_m2m()
            if type == 1:
                for b in order.books.all():
                    member.borrowed_books.add(b)

            return render(request, 'myapp/order_response.html', {'books': books, 'order': order})
        else:
            return render(request, 'myapp/placeorder.html', {'form': form})

    else:
        form = OrderForm()
        return render(request, 'myapp/placeorder.html', {'form': form})


def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data['rating']
            if rating <= 5 and rating >= 1:
                reviews = form.save(commit=False)
                books = reviews.book
                books.num_reviews += 1
                books.save()
                reviews.save()
                # return index(request)
                return redirect('myapp:index')
            else:
                RatingErr = "You must enter a rating between 1 and 5!"
                return render(request, 'myapp/review.html', {'form': form, 'RatingErr': RatingErr})
        else:
            # return HttpResponse('Please fill the form correctly')
            return render(request, 'myapp/review.html', {'form': form})

    else:
        form = ReviewForm()
        return render(request, 'myapp/review.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                dt = datetime.datetime.now()
                request.session['last_login'] = 'Last Login: ' + str(dt)
                request.session.set_expiry(3600)

                if 'next' in request.POST:
                    next_url= request.POST.get('next')
                    return HttpResponseRedirect(next_url)
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))


@login_required
def chk_reviews(request, book_id):
    try:
        if Member.objects.get(id=request.user.id):
            count = 0
            rating = 0
            bookData = {}
            for r in Review.objects.filter(book__id=book_id):
                count += 1
                rating += r.rating
            if rating != 0:
                bookData['avgRating'] = round(rating / count, 2)
            else:
                bookData['avgRating'] = 'Book is not rated'

            bookData['title'] = Book.objects.get(id=book_id).title
            bookData['price'] = Book.objects.get(id=book_id).price

            return render(request, 'myapp/chk_reviews.html',
                          {'member': request.user.first_name, 'book': bookData})
    except Member.DoesNotExist:
        return render(request, 'myapp/chk_reviews.html')
    except Book.DoesNotExist:
        return render(request, 'myapp/chk_reviews.html', {'member': request.user.first_name})

templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block title %}eBook APP About page{% endblock %}


{% block body_block %}
    <h1>This is an e-book application</h1> <br>
     <p>You lucky number is {{ myLuckyNum }}</p>
{% endblock %}

templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is an eBook APP.</title>
</head>
<body>
<H1>This is an eBook APP </H1>
<a href="/myapp/">Back_HardCoded</a>
<br>
<a href="{% url 'myapp:index'%}">Back</a>
</body>
</html>

templates/myapp/about0_OLD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is an eBook APP.</h1>
<a href="/myapp/">Index Page</a>

</body>
</html>

templates/myapp/chk_reviews.html
{% extends 'myapp/base.html' %}

{% block body_block %}

    {% if member %}
    {% if book %}

        <ul>
        <li><b>Title:</b> {{ book.title }}</li>
        <li><b>Price:</b> $ {{ book.price }}</li>
        <li><b>Avg. Rating:</b> {{ book.avgRating }}</li>
        </ul>
    {% else %}
        <h2 align="center">Book doesn't exist</h2>
    {% endif %}
{% else %}

    <h2 align="center">You are not a registered client!</h2>
{% endif %}

{% endblock %}

templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block title %}book details{% endblock %}


 {% block body_block %}
     <h1>Book Details</h1>
      <ol>
        <li>Title: {{ book.title }}</li>
        <li>Price: {{ book.price }} CAD</li>
        <li>Publisher: {{ book.publisher }}</li>
    </ol>

 {% endblock %}

templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Detail</title>
</head>
<body>
    <h1>Book Details</h1>
    <ol>
        <li>Title: {{ book.title }}</li>
        <li>Price: {{ book.price }} CAD</li>
        <li>Publisher: {{ book.publisher }}</li>
    </ol>

<a href="{% url 'myapp:index' %}">Home</a>
</body>
</html>

templates/myapp/findbooks.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:findbooks' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Find Books" />
    </form>

{% endblock %}

templates/myapp/index.html
{% extends 'myapp/base.html' %}


{% block myhdg %}
    Hello  {{ request.user.username }} <br>
    {{ last_login }}
{% endblock %}
{% block body_block %}

    {% if booklist %}
        <h2>List of Books</h2>
        <ol>
            {% for book  in booklist %}
                <li><a href="{% url 'myapp:detail' book.id %}"> {{book.title}} </a>
                    &nbsp;&nbsp;&nbsp;
                [<a href="{% url 'myapp:chk_reviews' book.id %}">Check Rating</a>]
                </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}

<!--
<p><a href="{%  url 'myapp:about' %}">About page</a></p>

    <li class="hbar1"><a href = "{% url 'myapp:findbooks' %}">Find Books with category</a><br/></li>
    -->
{% endblock %}

templates/myapp/index0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>eBook App</title>
</head>
<body>

    {% if booklist %}
        <h2>List of Books</h2>
        <ol>
            {% for book  in booklist %}
                <li><a href="{% url 'myapp:detail' book.id %}"> {{book.title}} </a></li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}


<p><a href="{%  url 'myapp:about' %}">About page</a></p>

</body>

</html>

templates/myapp/index0_OLD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>eBook App</title>
</head>
<body>

    {% if booklist %}
        <h2>List of Books</h2>
        <ol>
            {% for book  in booklist %}
                <li> {{book.title}} </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}
<p><a href="/myapp/about">About page(hardcoded)</a></p>
<a href="{% url 'myapp:about' %}">About Page</a>
</body>

</html>

templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block title %}eBook APP About page{% endblock %}


{% block body_block %}
    <form action="{% url 'myapp:login' %}" method="post">
        {% csrf_token %}
        <!--{{ form.as_p }}-->
        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        <br><br><br><br>
         Username:<input type="text" name="username"  value="" required/> <br><br>
         Password:<input type="password" name="password" value="" required/> <br><br>
        <input type="submit" name="submit" value="Login" />
    </form>
{% endblock %}

templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block title %}Books in order{% endblock %}


 {% block body_block %}

     {% if order %}
         Order ID: {{ order.id }}
         <br>Member name: {{ order.member.first_name }}
         <br>Order type:
         {% if order.order_type == 0 %}
             Purchase
         {%  else %}
             Borrowed
          {% endif %}

     {% endif %}
       {% if books %}
        <h2>List of Books in order({{ order.id }}) are:</h2>
            <ol>
            {% for book  in books %}

                <li> Title:{{book.title}}</li>
                Price:{{book.price}}<br>
                Number of Pages:{{book.num_pages}}<br><br>

            {% endfor %}
           </ol>


    {% else %}
        <strong>There are no books in the order</strong>
    {% endif %}

 {% endblock %}

templates/myapp/results.html
{% extends 'myapp/base.html' %}

{% block title %}Books{% endblock %}


 {% block body_block %}
       {% if booklist %}
        <h2>List of Books Requested by:{{ name }}, Category:{{ category }}, Max_Price:{{ max_price }}</h2>
            <ol>
            {% for book  in booklist %}

                <li> Title:{{book.title}}</li>
                Price:{{book.price}}<br>
                Number of Pages:{{book.num_pages}}<br><br>

            {% endfor %}
           </ol>


    {% else %}
        <strong>There are no available books for the search criteria!</strong>
    {% endif %}

 {% endblock %}

templates/myapp/review.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:review' %}" method="post">
        {% if RatingErr %}
            <h3 style="color:Red">{{ RatingErr }}</h3>
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Submit" />
    </form>

{% endblock %}